[project]
name = "worldonfire-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "eventregistry>=9.1",
    "fastapi[standard]>=0.120.4",
    "pydantic>=2.12.3",
    "supabase>=2.23.0",
]
